### PR TITLE
update Waves Platform markdown

### PR DESCRIPTION
**Pull request by vlzhr**

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
@vlzhr I'm not ot quite sure what you're fixing here? I had to do some fixes to your markdown, which this PR undoes some of.

**Comment by vlzhr** [comment]
hi, @ChrisChinchilla ! In the latest commit I'm:

1) replacing "get started" to the top
2) fixing "features" (because the word "features" is repeated twice in the current version
3) renaming "Resources" to the "Useful links"
4) actualising "Prizes offered" info

these are the final changes, sorry for so many pull requests

**Comment by ChrisChinchilla** [comment]
OK, let me make some tweaks to this, as I'd like to keep features at the top so it matches all the others. And the way the list is formatted is kind of odd and may not render that well, I also removed the unneeded HTML. 

Try these tweaks…

I'm not sure what the line `And access to them via API` refers to though? Then I can find a better way to show that.

**Comment by vlzhr** [comment]
Thanks for helping us. `And access to them via API` means that developers can also use Waves Products in their application by connecting their features using APIs.

**Comment by vlzhr** [comment]
Really like the way you formatted the list. Thanks!

**Comment by ChrisChinchilla** [comment]
OK, try this final change and if you're happy we'll merge

**Comment by vlzhr** [comment]
fixed the API point the last time. now we are really happy :)

**Pull request merged**
