### PR TITLE
add helpdesks and helpq link

### PR DESCRIPTION
**Pull request by pstehlik**

### CODE REVIEW

**Review by ligi — APPROVED** [review]

**Comment by ligi** [comment]
:+1:

**Comment by ChrisChinchilla** [comment]
This had syntax issues I was just pushing at the same time ;)

**Comment by ChrisChinchilla** [comment]
Oh, I think they just made it!

**Comment by ligi** [comment]
dam - my syntax checker said it is OK - need to update to yours

**Comment by ligi** [comment]
or perhaps we should add your syntax checker to the CI pipeline so merges are blocked when there are still issues

**Comment by ChrisChinchilla** [comment]
Nah, not for this repo. I thought I saw a list of 1. 1. 1, instead of 1. 2. 3. but maybe I imagined it.

**Comment by pstehlik** [comment]
yeah. the list in the markdown file is is just 1. 1. 1. - but the rendering of markdown will set it to the correctly numbered items.

**Pull request merged**
