### PR TITLE
corrected some typos

### PR DESCRIPTION
**Pull request by wisthsb1519**

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
@wisthsb1519 I can see the space, but is the user name change correct?

**Comment by wisthsb1519** [comment]
yes it is, sorry by 'corrected some typos', I meant corrected the space and the twitter handle in the commit message for Liz

**Review by ligi — APPROVED** [review]
Name change seems to make sense - when googling for "Elizabeth Baran" algorand shows up

**Comment by ligi** [comment]
:+1:

**Pull request merged**
